### ISSUE TITLE
Documenting BasicErrorController class in spring-boot project

### ISSUE THREAD

**Issue by sanju4112** [martypitt/swagger-springmvc#580] opened 2015-02-04 15:08 UTC
While using swagger-springmvc 9.1 in spring-boot project it is documenting BasicErrorController class.

![spring controller_1](https://cloud.githubusercontent.com/assets/10848324/6042768/68ef95e0-acad-11e4-8586-d92540185c39.PNG)
It will be nice to add method to ignore List of class. I tried customizing and added method to ignore class and it works fine.

**Comment by dilipkrish** [comment] 2015-02-04 21:09
@sanju4112 Try moving to 0.9.5. Also its not entirely clear to me what the problem is? Is this a feature request/bug?

>I tried customizing and added method to ignore class and it works fine.

What is it not working fine before you had to customize?

**Comment by sanju4112** [comment] 2015-02-09 15:50
My scenario is like this I have to import other projects in my project and i cant add swagger annotations to those projects and it follows similar request mapping pattern. So in such scenario how to exclude those controllers from getting documented. 
For this kind of scenario i added method to exclude class based on name by rewriting few class. 
It will be nice if this kind of feature is added to handle this kind of scenario.

**Comment by dilipkrish** [comment] 2015-02-10 02:29
You can use the [include patterns](https://github.com/martypitt/swagger-springmvc#swaggerspringmvcplugin-xml-configuration) to only document the paths you wish to document.

**Closed** 2015-02-28 19:46 UTC
Labels: question
