### ISSUE TITLE
Method level @RequestMapping not showing up in swagger-ui when value is blank

### ISSUE THREAD

**Issue by zeroklone** [martypitt/swagger-springmvc#582] opened 2015-02-06 11:02 UTC
This is a stripped down version of my code. The problem I am having is that the method all() does not show up  on the swagger-ui page.

```java
@RequestMapping(value = "/resources", method = GET)
@Api(value = "resource", description = "Resource for tracking resources.")
public class Resource{
    @RequestMapping
    @ApiOperation("...")
    public HttpEntity<Process>  all(){
    ...
    }
    @RequestMapping("/active")
    @ApiOperation("...")
    public HttpEntity<Process>  active(){
    ...
    }
   @RequestMapping("/idle")
    @ApiOperation("...")
   public HttpEntity<Process>  idle(){
    ...
    }
}
```

**Comment by dilipkrish** [comment] 2015-02-06 15:40
Closing this as it isnt reproducable. There may be something specific to the way you have the setup @ApiOperation annotation perhaps?

**Closed by dilipkrish** 2015-02-06 15:40 UTC
Labels: not-reproducable

**Comment by somas** [comment] 2015-06-19 16:51
I had the same issue, just in case if someone came here, I think the code works as is.

In my case the issue was caused by     

```private Predicate<String> paths() {
        return or(regex("/resources/.*"), regex("/xyz/.*"));
    } 
```
Key thing is the "/" after resources.When removed and made into 

```private Predicate<String> paths() {
        return or(regex("/resources.*"), regex("/xyz/.*"));
    } 
```
it all worked as expected. No need for extra @ApiOperation annotations
