### ISSUE TITLE
I have double record for each api end point

### ISSUE THREAD

**Issue by xhe** [martypitt/swagger-springmvc#565] opened 2015-01-23 17:25 UTC
I noticed the ajax call to 
http://localhost:8080/spring/api-docs/default/repositories gives me back duplicated record for each api method, this is json response:

{"apiVersion":"1.0","swaggerVersion":"1.2","basePath":"/spring","resourcePath":"/repositories","produces":["application/json"],"consumes":["application/json"],"apis":[{"path":"/repositories","description":"getAllRepositories","operations":[{"method":"GET","summary":"Get all repositories","notes":"Return all available repositories as list","nickname":"getAllRepositories","produces":["application/json"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":"OK","responseModel":"List"},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false","items":{"absoluteType":"Repository","type":"Repository","absoluteType":"Repository"},"absoluteType":"array","absoluteType":"array"}]},{"path":"/repositories","description":"getAllRepositories","operations":[{"method":"GET","summary":"Get all repositories","notes":"Return all available repositories as list","nickname":"getAllRepositories","produces":["application/json"],"consumes":["application/json"],"parameters":[],"responseMessages":[{"code":200,"message":"OK","responseModel":"List"},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false","items":{"absoluteType":"Repository","type":"Repository","absoluteType":"Repository"},"absoluteType":"array","absoluteType":"array"}]}],"models":{"Repository":{"id":"Repository","properties":{"name":{"type":"string","absoluteType":"string","absoluteType":"string","required":false,"description":null,"allowableValues":null},"id":{"type":"integer","format":"int32","absoluteType":"integer","absoluteType":"integer","required":false,"description":null,"allowableValues":null},"type":{"type":"string","absoluteType":"string","absoluteType":"string","required":false,"description":null,"allowableValues":null},"content":{"type":"string","absoluteType":"string","absoluteType":"string","required":false,"description":null,"allowableValues":null}},"description":""}}}

If you see this response carefully, you an see there are exactly two api insdie apis array, they are duplicated.

My config is:

@ComponentScan("com.spirenteng.controller")
public class SwaggerConfig {
	
	private SpringSwaggerConfig springSwaggerConfig;
	
	
	 /**
	    * Required to autowire SpringSwaggerConfig
	    */
	   @Autowired
	   public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
	      this.springSwaggerConfig = springSwaggerConfig;
	   }

	   /**
	    * Every SwaggerSpringMvcPlugin bean is picked up by the swagger-mvc framework - allowing for multiple
	    * swagger groups i.e. same code base multiple swagger resource listings.
	    */
	   @Bean
	   public SwaggerSpringMvcPlugin customImplementation(){
		   return new SwaggerSpringMvcPlugin(this.springSwaggerConfig)
           .apiInfo(apiInfo())
           .includePatterns(".*repo.*");
	   }
	   
	   private ApiInfo apiInfo() {
		      ApiInfo apiInfo = new ApiInfo(
		              "My Apps API Title",
		              "My Apps API Description",
		              "My Apps API terms of service",
		              "My Apps API Contact Email",
		              "My Apps API Licence Type",
		              "My Apps API License URL"
		        );
		      return apiInfo;
		    }
}

and my controller class is:

@Api(value = "repositories", description = "Provide repositories support through CRUD method.") // Swagger annotation
@RestController
public class RepositoryController {
	
	RepositoryService rs = new RepositoryService();
	
	 @RequestMapping(value="repositories",method = RequestMethod.GET,headers="Accept=application/json")
	 @ApiOperation(value = "Get all repositories", notes = "Return all available repositories as list")
	  public List<Repository> getAllRepositories() {  
	   List<Repository> repcontrositories= rs.getAllRepositories();
	   return repositories;
	  }
} 

Something wrong with your code or my settings are wrong?

**Comment by dilipkrish** [comment] 2015-01-23 17:39
Possibly this [issue response](https://github.com/martypitt/swagger-springmvc/issues/296#issuecomment-70036381) might help.

**Comment by xhe** [comment] 2015-01-23 17:48
Thanks,
Removing @EnableWebMvc will help.
Maybe we need to update  the doc and remove this tag completely?

**Comment by dilipkrish** [comment] 2015-01-25 14:48
Closing this as its a duplicate of #296

**Closed by dilipkrish** 2015-01-25 14:48 UTC
Labels: duplicate

**Comment by JavaHelper** [comment] 2016-01-19 15:53
I still facing the same issue although I removed @EnableWebMvc. I am using 0.9.4 version of Spring MVC Swagger. Please help

**Comment by dilipkrish** [comment] 2016-01-19 16:51
At the very least you should be in version `1.0.2` (which supports swagger 1.2). The current version of the library is 2.3.1

This is because you have two spring contexts. It entirely depends on how you have your project setup. Usually disabling the @EnableWebMvc fixes it. Do you perhaps have a [`ContextLoaderListener`](http://stackoverflow.com/a/9016202/19219) that you may no longer need? What version of spring are you using?

**Comment by JavaHelper** [comment] 2016-01-19 17:44
Even I am using latest version 1.0.2. I see same behavior. 

```
<dependency>
	<groupId>com.mangofactory</groupId>
	<artifactId>swagger-springmvc</artifactId>
	<version>1.0.2</version>
</dependency>
<repositories>
	<repository>
	  <id>jcenter-release</id>
	  <name>jcenter</name>
	  <url>http://oss.jfrog.org/artifactory/oss-release-local/</url>
	</repository>
</repositories>
```
In web.xml, please guide and according to this link http://stackoverflow.com/questions/26720090/a-simple-way-to-implement-swagger-in-a-spring-mvc-application, I am using 
```
@Configuration
@EnableSwagger
public class SwaggerConfig {
	private SpringSwaggerConfig springSwaggerConfig;

	@Autowired
	public void setSpringSwaggerConfig(SpringSwaggerConfig springSwaggerConfig) {
		this.springSwaggerConfig = springSwaggerConfig;
	}

	@Bean
	public SwaggerSpringMvcPlugin customImplementation() {
		return new SwaggerSpringMvcPlugin(this.springSwaggerConfig).apiInfo(apiInfo()).includePatterns(".*");
	}

	private ApiInfo apiInfo() {
		return new ApiInfo(
				"API", // title
				null, // description
				null,  // termsOfServiceUrl
				"support@support.com", // contact
				"License", // license
			         null; // licenseUrl
	}
}
```

```
<context-param>
        <param-name>contextConfigLocation</param-name>
        <param-value>
        classpath:spring/app-config.xml
        </param-value>
    </context-param>
    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>
    <servlet>
        <servlet-name>dispatcherServlet</servlet-name>
        <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
        <init-param>
            <param-name>contextConfigLocation</param-name>
            <param-value>/WEB-INF/mvc-config.xml</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>dispatcherServlet</servlet-name>
        <url-pattern>/</url-pattern>
    </servlet-mapping>
```

**Comment by dilipkrish** [comment] 2016-01-19 17:55
Do you have a repository you can share?

**Comment by JavaHelper** [comment] 2016-01-19 17:56
No I can't share my code, its clients code

**Comment by dilipkrish** [comment] 2016-01-19 17:58
Can you recreate the issue with a simple non-client specific code. One controller one method and your configuration like you have it without any client specific code?

**Comment by JavaHelper** [comment] 2016-01-19 18:52
I am not able to reproduced that issue in another sample code. Its working fine there, but in my clients code context loading is twice. How we can prevent that to be recognized by Swagger ?

**Comment by dilipkrish** [comment] 2016-01-19 19:02
There is obviously something thats configured differently in your _client application_. Hard to really say without isolating whats causing this.

**Comment by JavaHelper** [comment] 2016-01-19 19:17
Hey, I find the issue. I had implemented CustomExceptionHandler (to catch all Restful services error) and only that class was having @EnableWebMvc annotation when I removed that I see duplicates are gone. I wonder @EnableWebMvc on that class affecting whole code?

**Comment by dilipkrish** [comment] 2016-01-19 19:38
woot!
