### ISSUE TITLE
swagger spec version 2.0

### ISSUE THREAD

**Issue by i022098** [martypitt/swagger-springmvc#578] opened 2015-02-03 11:37 UTC
Hello,
it looks like you are using swagger spec 1.2
can you tell me when you will move to version 2.0?
i have a RequestParam that is an array of enums.
the json return is

{
                            "items": {
                                "type": "string",
                                "absoluteType": "string"
                            },
                            "absoluteType": "array",
                            "name": "measurements",
                            "description": "measurementsArray",
                            "defaultValue": "",
                            "required": false,
                            "allowMultiple": true,
                            "enum": [
                                "roi",
                                "numOfExecutions",
                                "avgExecutionTime",
                                "resultDistribution"
                            ],
                            "paramType": "query",
                            "paramAccess": null
                        }
so the "type" property is inside the "items" object,
and i understand from  (@webron)  from swagger-ui that there might be a problem here
Thanks

**Comment by dilipkrish** [comment] 2015-02-03 13:24
@i022098 We should be supporting pretty soon. it see work in progress here #538

**Comment by dilipkrish** [comment] 2015-02-03 15:58
Duplicate of #444

**Closed by dilipkrish** 2015-02-03 15:58 UTC
Labels: duplicate

**Comment by webron** [comment] 2015-02-03 18:00
@dilipkrish - I'm kinda curious about the appearance of the `absoluteType` in the above example. From what I understand, this is the output of swagger-springmvc 0.9.5.

**Comment by dilipkrish** [comment] 2015-02-03 22:56
@webron I'm curious too :) All of our [test cases](https://github.com/martypitt/swagger-springmvc/tree/master/swagger-contract-tests/src/test/resources/contract/swagger) do not have any trace of that element. Seems like an _using-the-wrong-ObjectMapper_ issue.

Just a bit of background on what that work in progress is about. We had a little bit of friction trying to coerce our existing logic to infer the service models to fit into the *NEW* serialization model that swagger-core provides out of the box. Basically, We dint want to keep changing the logic to infer the service model every time the spec changed. 

So we ended up going the route of decoupling the over-the-wire representation of the spec from the actual service model that we infer. That way its all we have to (in theory :smile:) is to create a new mapping layer for swagger 2.0. Its getting there, but still a bit of ways out.

**Comment by webron** [comment] 2015-02-03 23:14
Okay. Let us know if you need any assistance.

**Comment by mousycoder** [comment] 2015-05-28 11:00
{"apiVersion":"1.0","swaggerVersion":"1.2","basePath":"/server","resourcePath":"/sc/commodity","produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":[],"apis":[{"path":"/sc/commodity/addCommodity","description":"addCommodity","operations":[{"method":"POST","summary":"添加商品","notes":"添加商品","responseClass":"string","nickname":"addCommodity","position":0,"produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":{},"parameters":[{"parameterType":{"absoluteType":"string"},"name":"body","description":"postData","defaultValue":"","required":false,"allowMultiple":false,"allowableValues":null,"paramType":"body","paramAccess":null}],"responseMessages":[{"code":200,"message":null,"responseModel":"string"},{"code":201,"message":"Created","responseModel":null},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false"}],"hidden":false},{"path":"/sc/commodity/createCommodityCode","description":"createCommodityBarCode","operations":[{"method":"POST","summary":"生成商品条形码","notes":"生成商品条形码","responseClass":"string","nickname":"createCommodityBarCode","position":0,"produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":{},"parameters":[{"parameterType":{"absoluteType":"string"},"name":"body","description":"postData","defaultValue":"","required":false,"allowMultiple":false,"allowableValues":null,"paramType":"body","paramAccess":null}],"responseMessages":[{"code":200,"message":null,"responseModel":"string"},{"code":201,"message":"Created","responseModel":null},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false"}],"hidden":false},{"path":"/sc/commodity/getCodeImg","description":"getCommodityCodeImg","operations":[{"method":"POST","summary":"获取商品编码图片地址","notes":"获取商品编码图片地址","responseClass":"string","nickname":"getCommodityCodeImg","position":0,"produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":{},"parameters":[{"parameterType":{"absoluteType":"string"},"name":"body","description":"postData","defaultValue":"","required":false,"allowMultiple":false,"allowableValues":null,"paramType":"body","paramAccess":null}],"responseMessages":[{"code":200,"message":null,"responseModel":"string"},{"code":201,"message":"Created","responseModel":null},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false"}],"hidden":false},{"path":"/sc/commodity/getCommodity","description":"getCommodity","operations":[{"method":"POST","summary":"获取商品","notes":"获取商品信息","responseClass":"ResultDTO?CommoditiesDTO?","nickname":"getCommodity","position":0,"produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":{},"parameters":[{"parameterType":{"absoluteType":"string"},"name":"body","description":"postData","defaultValue":"","required":false,"allowMultiple":false,"allowableValues":null,"paramType":"body","paramAccess":null}],"responseMessages":[{"code":200,"message":null,"responseModel":"ResultDTO?CommoditiesDTO?"},{"code":201,"message":"Created","responseModel":null},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false"}],"hidden":false},{"path":"/sc/commodity/getCommodityAssort","description":"getCommodityAssort","operations":[{"method":"POST","summary":"获取商品分类","notes":"获取商品分类","responseClass":"string","nickname":"getCommodityAssort","position":0,"produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":{},"parameters":[{"parameterType":{"absoluteType":"string"},"name":"body","description":"postData","defaultValue":"","required":false,"allowMultiple":false,"allowableValues":null,"paramType":"body","paramAccess":null}],"responseMessages":[{"code":200,"message":null,"responseModel":"string"},{"code":201,"message":"Created","responseModel":null},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false"}],"hidden":false},{"path":"/sc/commodity/getProperty","description":"getVersion","operations":[{"method":"POST","summary":"获取商品版本","notes":"获取商品版本","responseClass":"string","nickname":"getVersion","position":0,"produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":{},"parameters":[{"parameterType":{"absoluteType":"string"},"name":"body","description":"postData","defaultValue":"","required":false,"allowMultiple":false,"allowableValues":null,"paramType":"body","paramAccess":null}],"responseMessages":[{"code":200,"message":null,"responseModel":"string"},{"code":201,"message":"Created","responseModel":null},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false"}],"hidden":false},{"path":"/sc/commodity/getPublicPics","description":"getPublicPics","operations":[{"method":"POST","summary":"通过条形码获取商品图片","notes":"通过条形码获取商品图片","responseClass":"string","nickname":"getPublicPics","position":0,"produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":{},"parameters":[{"parameterType":{"absoluteType":"string"},"name":"body","description":"postData","defaultValue":"","required":false,"allowMultiple":false,"allowableValues":null,"paramType":"body","paramAccess":null}],"responseMessages":[{"code":200,"message":null,"responseModel":"string"},{"code":201,"message":"Created","responseModel":null},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false"}],"hidden":false},{"path":"/sc/commodity/updateCommodityInfo","description":"updateCommodityInfo","operations":[{"method":"POST","summary":"修改商品信息","notes":"修改商品信息","responseClass":"string","nickname":"updateCommodityInfo","position":0,"produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":{},"parameters":[{"parameterType":{"absoluteType":"string"},"name":"body","description":"postData","defaultValue":"","required":false,"allowMultiple":false,"allowableValues":null,"paramType":"body","paramAccess":null}],"responseMessages":[{"code":200,"message":null,"responseModel":"string"},{"code":201,"message":"Created","responseModel":null},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false"}],"hidden":false},{"path":"/sc/commodity/updateCommodityStatus","description":"updateCommodityStatus","operations":[{"method":"POST","summary":"更新商品状态","notes":"更新商品状态","responseClass":"string","nickname":"updateCommodityStatus","position":0,"produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":{},"parameters":[{"parameterType":{"absoluteType":"string"},"name":"body","description":"postData","defaultValue":"","required":false,"allowMultiple":false,"allowableValues":null,"paramType":"body","paramAccess":null}],"responseMessages":[{"code":200,"message":null,"responseModel":"string"},{"code":201,"message":"Created","responseModel":null},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false"}],"hidden":false},{"path":"/sc/commodity/uploadImg","description":"uploadCommodityImg","operations":[{"method":"POST","summary":"上传商品图片","notes":"上传商品图片","responseClass":"string","nickname":"uploadCommodityImg","position":0,"produces":["*/*"],"consumes":["application/json"],"protocol":[],"authorizations":{},"parameters":[],"responseMessages":[{"code":200,"message":null,"responseModel":"string"},{"code":201,"message":"Created","responseModel":null},{"code":401,"message":"Unauthorized","responseModel":null},{"code":403,"message":"Forbidden","responseModel":null},{"code":404,"message":"Not Found","responseModel":null}],"deprecated":"false"}],"hidden":false}],"models":{"CommoditiesDTO":{"id":"CommoditiesDTO","name":"CommoditiesDTO","qualifiedType":"com.weitoo.common.dto.commodity.CommoditiesDTO","properties":{"count":{"type":{"absoluteType":"integer"},"qualifiedType":"int","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"commodityDTO":{"type":{"absoluteType":"List"},"qualifiedType":"java.util.List<com.weitoo.common.dto.commodity.CommodityDTO>","position":0,"required":false,"description":null,"allowableValues":null,"items":{"type":{"absoluteType":"CommodityDTO"},"absoluteType":"CommodityDTO"}}},"description":"","baseModel":"","discriminator":"","subTypes":[]},"CommodityDTO":{"id":"CommodityDTO","name":"CommodityDTO","qualifiedType":"com.weitoo.common.dto.commodity.CommodityDTO","properties":{"name":{"type":{"absoluteType":"string"},"qualifiedType":"java.lang.String","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"id":{"type":{"absoluteType":"integer"},"qualifiedType":"long","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"status":{"type":{"absoluteType":"integer"},"qualifiedType":"int","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"assortName":{"type":{"absoluteType":"string"},"qualifiedType":"java.lang.String","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"parentAssortName":{"type":{"absoluteType":"string"},"qualifiedType":"java.lang.String","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"picPath":{"type":{"absoluteType":"string"},"qualifiedType":"java.lang.String","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"assortId":{"type":{"absoluteType":"integer"},"qualifiedType":"long","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"barcode":{"type":{"absoluteType":"string"},"qualifiedType":"java.lang.String","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"price":{"type":{"absoluteType":"number"},"qualifiedType":"double","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"stock":{"type":{"absoluteType":"integer"},"qualifiedType":"int","position":0,"required":false,"description":null,"allowableValues":null,"items":null}},"description":"","baseModel":"","discriminator":"","subTypes":[]},"ResultDTO?CommoditiesDTO?":{"id":"ResultDTO?CommoditiesDTO?","name":"ResultDTO?CommoditiesDTO?","qualifiedType":"com.weitoo.common.dto.ResultDTO","properties":{"message":{"type":{"absoluteType":"string"},"qualifiedType":"java.lang.String","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"data":{"type":{"absoluteType":"CommoditiesDTO"},"qualifiedType":"com.weitoo.common.dto.commodity.CommoditiesDTO","position":0,"required":false,"description":null,"allowableValues":null,"items":null},"status":{"type":{"absoluteType":"integer"},"qualifiedType":"int","position":0,"required":false,"description":null,"allowableValues":null,"items":null}},"description":"","baseModel":"","discriminator":"","subTypes":[]}},"description":null,"position":0}



为何出现的是 absoluteType 导致js出错 Uncaught TypeError: this.dataType.toLowerCase is not a function 继而不能点开接口  这个问题遇到很纠结 纠结了2个星期了

**Comment by xavierzhao** [comment] 2016-03-19 01:20
@mousycoder 请问你的问题解决没？我也有此问题？麻烦分享下
