### ISSUE TITLE
Support for Swagger 2.0

### ISSUE THREAD

**Issue by ndhar-1** [martypitt/swagger-springmvc#581] opened 2015-02-04 23:52 UTC
I believe the latest version of swagger-springmvc does not support Swagger 2.0. When will the supported version be released ?

**Comment by robert-morschel** [comment] 2015-02-06 10:19
+1

**Comment by dilipkrish** [comment] 2015-02-06 15:45
Closing this as its a duplicate of #444

**Closed by dilipkrish** 2015-02-06 15:45 UTC
